/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'failed';

export interface ShadowArtifacts {
  context_summary?: string;
  checklist?: {
    id: string;
    text: string;
    completed: boolean;
  }[];
  planning_strategy?: string[];
  starter_code?: string;
  ai_recommends?: string;
  command_logs?: {
    timestamp: string;
    command: string;
    output: string;
  }[];
}

export interface Task {
  id: string; // uuid
  user_id: string; // uuid
  title: string; // text
  raw_input: string; // text
  deadline: string; // timestamp (ISO string)
  status: TaskStatus;
  priority_score: number; // integer 1-100
  shadow_artifacts: ShadowArtifacts; // jsonb
  collision_warning?: string; // Optional warning generated by AI
}

export interface HabitData {
  timestamps: string[];
  activeStreak: number;
  maxStreak: number;
}

export interface UserProfile {
  user_id: string;
  hasCompletedOnboarding?: boolean;
  phoneNumber?: string;
  email?: string;
  isNewUser?: boolean;
  habits: {
    algorithms: HabitData;
    docs: HabitData;
    commits: HabitData;
  };
}

export interface Database {
  public: {
    Tables: {
      tasks: {
        Row: Task;
        Insert: Omit<Task, 'id'> & { id?: string };
        Update: Partial<Task>;
      };
    };
  };
}
